FROM python:latest


WORKDIR ./dashboard

COPY requirements.txt .
RUN pip3 install -r requirements.txt

EXPOSE 8501 

COPY connect.py .
COPY dashboard.py .

# Instructions for running streamlit dashboard
CMD streamlit run dashboard.py --server.port 8501




# RUN LOCALLY
    # docker build -t stack-exchange-dashboard-local .
    # docker image ls
    # docker run -it -p 8501:8501 --env-file .env stack-exchange-dashboard-local

# AWS ECR PUSH COMMANDS:
    # aws ecr get-login-password --region eu-west-2 | docker login --username AWS --password-stdin 129033205317.dkr.ecr.eu-west-2.amazonaws.com
    # docker build --platform "linux/amd64" -t c11-fariha-stack-exchange-dashboard . 
    # docker tag c11-fariha-stack-exchange-dashboard:latest 129033205317.dkr.ecr.eu-west-2.amazonaws.com/c11-fariha-stack-exchange-dashboard:latest
    # docker push 129033205317.dkr.ecr.eu-west-2.amazonaws.com/c11-fariha-stack-exchange-dashboard:latest

# external link: 3.10.208.9:8501 

